### ISSUE TITLE
[BUG] actor_ref在创建之后，通过actor_ref方法获取时，uid丢失，变成了None

### ISSUE THREAD

**Issue by wuyouMaster** [xorbitsai/xoscar#103]
### Describe the bug
xinference框架在使用xoscar创建worker_ref之后，再通过actor_ref方法获取worker_ref应用时，能够获取引用，但是这个ref的uid变成了None

library versions:
xinference==0.13.3
xoscar==0.3.2

### Additional context
![2024-08-29_13-42](https://github.com/user-attachments/assets/87d9b53a-4b69-459b-a8fc-06165f518141)
![2024-08-29_13-42_1](https://github.com/user-attachments/assets/7880ec21-4e8d-4de8-a275-0a2962759ef0)
![2024-08-29_13-45](https://github.com/user-attachments/assets/6b2ba768-03e3-40e2-bf4f-adc9b4a4b9df)
![2024-08-29_13-44](https://github.com/user-attachments/assets/1233d3ad-ff49-4aa5-9427-dc3288dc4111)

**Comment by qinxuye** [comment]
问题在 xinference repo 里进行了修复，实际上不是 Xoscar 的问题。

原因在于 Xinference 里的几个 Actor 使用了 `uid()` 方法，但 `uid` 是 `xoscar.Actor` 的属性，被覆盖掉了。
