### ISSUE TITLE
BUG: xoscar installed by pypi not contains xoscar_pygloo.so

### ISSUE THREAD

**Issue by ChengjieLi28** [xorbitsai/xoscar#61]
Note that the issue tracker is NOT the place for general support.  For
discussions about development, questions about usage, or any general questions,
contact us on https://discuss.xorbits.io/.

```
pip install xoscar
```
on a new Linux machine. And I found that there is no pygloo related so file under ``xoscar/collective`` dir.

<img width="1378" alt="image" src="https://github.com/xorbitsai/xoscar/assets/109656400/690ecd04-672c-4a16-a44c-1a91454a250c">

cc @YibinLiu666

**Comment by YibinLiu666** [comment]
take
