### ISSUE TITLE
DOC: Add build from source guidance

### ISSUE THREAD

**Issue by luweizheng** [xorbitsai/xoscar#70]
As there are some C++ code in this project, I hope there is a "build from source" part  in the doc or readme. Thanks!

**Comment by luweizheng** [comment]
I mean, what dependency or compiler version developers should prepare.

**Comment by ChengjieLi28** [comment]
Hi, @luweizheng . I make a PR about this issue. The information about how to build xoscar from source will be shown in the README.md.
